remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title: John Marquess Github Page
email: john@marquess.me
description: >- # this means to ignore newlines until "baseurl:"
  This is the site description.
baseurl: "/jekyll_docker_website" # the subpath of your site, e.g. /blog
url: "https://johnmarquess.github.io" # the base hostname & protocol for your site, e.g. http://example.com


github_username:  johnmarquess

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Site settings
locale: "en-AU"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true